"""empty message

Revision ID: 01a7bdb1ddbe
Revises: c89c709a789c
Create Date: 2024-04-09 12:51:51.330806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a7bdb1ddbe'
down_revision = 'c89c709a789c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('money', sa.Integer(), nullable=True))
        batch_op.drop_column('reward_points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_points', sa.INTEGER(), nullable=True))
        batch_op.drop_column('money')

    # ### end Alembic commands ###
