"""empty message

Revision ID: aa11de6aacd2
Revises: 01a7bdb1ddbe
Create Date: 2024-04-28 20:30:54.611391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa11de6aacd2'
down_revision = '01a7bdb1ddbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('reward_type', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Float(precision=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_user_id'))
        batch_op.drop_index(batch_op.f('ix_reward_timestamp'))

    op.drop_table('reward')
    # ### end Alembic commands ###
